### ISSUE TITLE
零售行为发现

### ISSUE THREAD

**Issue by jackhackson** [vesoft-inc/nebula-community#56]
队名：AI-COM
项目名：零售行为发现
项目介绍：采用nebula代替传统数据库对零售商业行为进行智能发现
团队成员：
  梅影零落: 计算数学大三学生

Team Name: AI-COM
Project Name: Retail behavior discovery
Project Introduction:Using Nebula instead of traditional database to discover retail business behavior intelligently
Team Members:
   Michael: junior students of Computational Mathematics

**Comment by QingZ11** [comment]
😂  Nebula Hackathon 2021 的参赛队伍报名以 comment 形式提交到这个 issue 哈 [https://github.com/vesoft-inc/nebula-community/issues/38](https://github.com/vesoft-inc/nebula-community/issues/38)

jackhackson 你的 issue 关闭啦
