### ISSUE TITLE
【Nebula Hackathon 2021 RFC】悬挂边和超级节点

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-community#57]
## 项目名称

悬挂边和超级节点

## 项目简介

优化和修改存储层的数据结构，处理悬挂边的问题，并提供counter判断点的出入度

## 项目背景

nebula  storaged
1.  有悬挂边问题
2. 没有办法判断是否是超级节点

## 悬挂边
```
(src)-[edge]->           有起点，有边，没有终点
-[edge]->(dst)           没有起点，有边，有终点
-[edge]->               没有起点，没有终点，有边
```
### 原因：
```
因为图元素建模的时候，EdgeA_Out 的存在性和srcVertex 是两个独立的key。
有可能
 graphd只插入了边EdgeA，没插入srcVertx
 graphd drop tag操作不完备   
 删除Vertex和边的操作不原子。导致垃圾key的存在。 边key没删成功，把点key删成功了。
```

## 每个点的出度、入度（实时的）统计值——特别是超级节点
```
场景1. 判断一个点是否是超级节点？
场景2. 找到有哪些超级节点？
场景3. 最短路径等算法的时候，默认BFS，走到超级节点就先暂停BFS，改成DFS或者采样。
场景4. 执行计划CBO的时候，count是Cost的一个重要参数。
场景5: 删除一个超级节点（和周围的边），rpc超时参数值处理设置。
```
### 原因：
```
EdgeA_Out 是单独的Key
EdgeA_Out1
EdgeA_Out2
EdgeA_Out3

EdgeA_Outn
对于每个点，不做prefix scan不知道n是多少。——除非离线扫描。
```

## 项目设计

参考了Janusgraph 的建模方式，还有neo4j的建模方式，加一个ref_key来做点相关边的原子操作。

由于兼容原有数据，可以设计不停机升级。

## 项目测试

少量优化下，看读写性能大约会减慢多少。

## <.....>

更多你想补充说明的内容。

**Comment by QingZ11** [comment]
这个活动已经结束，issue 先行关闭了，所有参赛的 rfc 和队伍资料参考链接：https://github.com/vesoft-inc/nebula-community/blob/master/zh-Hans/hackathon/hackathon-2021/teams.md
