### ISSUE TITLE
【Nebula Hackathon 2021 RFC】如何吊打nebula的深度查询

### ISSUE THREAD

**Issue by critical27** [vesoft-inc/nebula-community#73]
### 项目名称
如何吊打nebula的深度查询

### 项目简介
增加一个节点用于存储图拓扑，提升深度查询性能

### 项目背景
nebula的深度查询是bfs，需要在graphd和storaged之间通过多次rpc才能获取所有数据。通过增加单机图拓扑节点（以raft的learner形式获取最新改动），所有图的遍历都可以在这个单机节点完成。

### 项目价值
期望在深度查询性能上能得到大幅提升，比如
```
go 5 steps from vId over *
go 5 steps from vId over * | yield count(*)
go 5 steps from vId over e1 yield e1.p1, $$.t1.p1
get subgraph 5 steps from vId
```

### 项目设计
TBD

### 项目测试
相同数据集对比正常部署nebula和增加单机图拓扑节点的nebula

**Comment by whitewum** [comment]
一般来说，为了减少图VID的内存占用（你可以算下 32bit->32bit 一条边的内存占用），会 进行id编码，128bit 编码成32bit。

编码映射可以放在storaged里面

**Comment by QingZ11** [comment]
这个活动已经结束，issue 先行关闭了，所有参赛的 rfc 和队伍资料参考链接：https://github.com/vesoft-inc/nebula-community/blob/master/zh-Hans/hackathon/hackathon-2021/teams.md
