### ISSUE TITLE
update issue template

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-community#81]
ref: https://github.com/louislam/uptime-kuma/edit/master/.github/ISSUE_TEMPLATE/feature_request.yaml

<img width="944" alt="Screen Shot 2021-12-29 at 10 13 00 AM" src="https://user-images.githubusercontent.com/1651790/147620917-996e121e-cb26-43b2-b293-ea9441cf723a.png">

**Comment by wey-gu** [comment]
cc @Sophie-Xie @jamieliu1023

**Comment by Sophie-Xie** [comment]
Looks so cool!
