### ISSUE TITLE
Some suggestions to nebula-community

### ISSUE THREAD

**Issue by jyz0309** [vesoft-inc/nebula-community#9]
I'm interested in Nebula and have looked at it in the last few days. I think Nebula-Community is not doing a very good job, here are my two small suggestions: 
1. Github Issue, I think the label classification of the current Issue is not particularly friendly to newcomers, for example, when I want to find whether there is a relatively simple bug in Nebula's Issue, I did not find the easy issue ( because there is no easy/ For example, when I tried to find out if there were any easier bugs in Nebula's Issue, I didn't find an easy issue (because there was no easy/medium/hard label) and the good first issue never seemed to appear :) 
2. doc and blog, I have read this [blog](https://nebula-graph.com.cn/posts/how-to-read-nebula-graph-source-code/), but be honest, I only have an impression of a general source code flow after reading it, but not a good understanding of the module I want to know. So I would suggest to split the project into modules and do a source code analysis of each module, and in each issue, give a label according to the module involved, so that it is more friendly for Contributor.

我对 Nebula 比较感兴趣，并且这几天也看了一下。我觉得 Nebula-Community 并没有做的非常好，以下我的两点小小的建议：
1. Github Issue，我觉得目前 Issue 的 label 分类并不是特别的友好，对新人不友善，举个例子，当我想要在 Nebula 的 Issue 中翻找有没有比较简单的 bug 的时候，我没有找到 easy 的 issue( 因为没有 easy/medium/hard 的 label )，而 good first issue 好像从没有出现过 :) 
2. 文档博客，我翻看过 Nebula 的源码解析的文档，但坦言说，看完之后我只对于一个大概的源码流向有了印象，而对我想要知道的模块并没有很了解。所以个人建议，可以将项目拆分成各个模块，并对各个模块进行粗略的源码分析，并且在每个 issue 中，根据涉及到的模块打 label，这样对于 Contributor 来说更友善。

**Comment by jyz0309** [comment]
Just personal suggestion~ If you want  https://github.com/vesoft-inc/nebula-community/issues/2 at the top position, I will close it ~ Just @ me :) make Nebula great :)

**Comment by wey-gu** [comment]
Dear @jyz0309,

Tons of thanks for your valuable thoughts and ideas shared here, we really treasure and appreciate them.

For 1. we are working on them, and hopefully soon, there will be properly organized issues/tasks labeled on both core and utils repos.
For 2. It's also what we were preparing for, and your idea here had made us rethink its priorities, hopefully, we'll have more contents dive into different function blocks of the nebula graph in the future.

Please stay tuned! And I would like to notify you when we have some progress here.

Thank you again :).
Cheers!
Nebula Commnunity
